version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
#    volumes:
#      - redis_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    container_name: mssql
    environment:
      SA_PASSWORD: "Admin12345" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
#    volumes:
#      - mssql_data:/var/opt/mssql

#volumes:
#  redis_data:
#  mssql_data