version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    container_name: mssql
    environment:
      SA_PASSWORD: "Admin12345" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  cache-service-api:
    build: 
      context: .
      dockerfile: CacheService.API/Dockerfile
    environment:
      Redis__Url: redis
    ports:
      - "1433:1433"
    depends_on: 
      - redis

  webshop-service-api:
    build: 
      context: .
      dockerfile: CacheService.API/Dockerfile
    environment:
      - RabbitMQ__Host=rabbitmq 
      - RabbitMQ__Username=guest 
      - RabbitMQ__Password=guest 
    depends_on:
      - rabbitmq 

  rabbitmq:
    image: rabbitmq:management 
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

